# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Credentials:
            algorithm: bcrypt
            cost: 12

    providers:
        nogame_credentials:
            entity:
                class: AppBundle\Entity\Credentials

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        nogame:
            pattern:    ^/
            anonymous: ~
            form_login:
                provider: nogame_credentials
                login_path: nogame_login
                check_path: nogame_login_check
                failure_path: nogame_login
                use_referer: true
            logout:
                path:   nogame_logout
                target: /

    access_control:
        - { path: ^/account/*, roles: [ROLE_USER] }
        - { path: ^/, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }