services:
    nogame.validator.unique_value:
        class: AppBundle\Validator\Constraints\UniqueValueValidator
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: unique_value }